-- Step 2 of 2: APPLY. Run this against the LIVE (already-fixed) database (invite_prd) ONLY,
-- after crm_restore_staging_dump.sql (generated by restore_crm_info_extract.sql) has already
-- been run against invite_prd to populate the crm_restore_staging table. This script never
-- touches the backup -- everything from here on is scoped to this one database, so there is
-- no possibility of the earlier cross-database ambiguity bug.
--
-- Full sequence:
--   mysql -N -u root invite_prd_backup < server/src/test/resources/restore_crm_info_extract.sql > crm_restore_staging_dump.sql
--   mysql -u root invite_prd < crm_restore_staging_dump.sql
--   mysql -u root invite_prd < server/src/test/resources/restore_crm_info_apply.sql
--
-- `users` has a UNIQUE constraint `users_unique_crm_contact_profile` on
-- (crm_contact_id, organisation_id) (see V55_0__crm_roles_users.sql). Existing non-NULL values
-- on the live user are never overwritten. A fill is skipped -- and flagged for manual review --
-- if it would produce a pair that already belongs to a different user, or that two different
-- staged rows would both try to apply (checked via the temp table below, within this database).

-- ============================================================================
-- DRY RUN -- read-only, run this first and review before proceeding
-- ============================================================================

-- Sanity check: crm_restore_staging must already be populated by crm_restore_staging_dump.sql
SELECT COUNT(*) AS staged_rows FROM crm_restore_staging;

-- Every staged row matched to its live user, with the value each column would end up with
-- (existing live value wins if already set)
CREATE TEMPORARY TABLE crm_restore_map AS
SELECT s.target_sub,
       u.id                                            AS target_id,
       s.crm_contact_id                                AS staged_crm_contact_id,
       s.organisation_id                                AS staged_organisation_id,
       u.crm_contact_id                                 AS current_crm_contact_id,
       u.organisation_id                                AS current_organisation_id,
       COALESCE(u.crm_contact_id, s.crm_contact_id)     AS new_crm_contact_id,
       COALESCE(u.organisation_id, s.organisation_id)   AS new_organisation_id
FROM crm_restore_staging s
         JOIN users u ON u.sub = s.target_sub;

ALTER TABLE crm_restore_map
    ADD COLUMN has_unique_conflict BOOLEAN DEFAULT FALSE;

-- Conflict against a DIFFERENT existing user's (crm_contact_id, organisation_id) pair
UPDATE crm_restore_map m
SET has_unique_conflict = EXISTS (SELECT 1
                                   FROM users u2
                                   WHERE u2.id <> m.target_id
                                     AND m.new_crm_contact_id IS NOT NULL
                                     AND m.new_organisation_id IS NOT NULL
                                     AND u2.crm_contact_id = m.new_crm_contact_id
                                     AND u2.organisation_id = m.new_organisation_id);

-- Conflict WITHIN the proposed updates themselves (two staged rows resolving to the same pair
-- for two different target users)
UPDATE crm_restore_map m
SET has_unique_conflict = TRUE
WHERE m.new_crm_contact_id IS NOT NULL
  AND m.new_organisation_id IS NOT NULL
  AND EXISTS (SELECT 1
              FROM crm_restore_map m2
              WHERE m2.target_id <> m.target_id
                AND m2.new_crm_contact_id = m.new_crm_contact_id
                AND m2.new_organisation_id = m.new_organisation_id);

-- All candidate rows
SELECT *
FROM crm_restore_map;

-- Staged rows with no matching live user at all -- shouldn't happen, investigate manually
SELECT s.*
FROM crm_restore_staging s
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.sub = s.target_sub);

-- Field-level conflicts: the live user already has a non-NULL value differing from the staged
-- value. Never overwritten -- review manually.
SELECT *
FROM crm_restore_map
WHERE (current_crm_contact_id IS NOT NULL AND current_crm_contact_id <> staged_crm_contact_id)
   OR (current_organisation_id IS NOT NULL AND current_organisation_id <> staged_organisation_id);

-- Unique-constraint conflicts (against another existing user, or against another staged row).
-- Excluded from FIX -- review manually.
SELECT *
FROM crm_restore_map
WHERE has_unique_conflict = TRUE;

-- Rows that will actually be updated by FIX
SELECT *
FROM crm_restore_map
WHERE has_unique_conflict = FALSE
  AND ((current_crm_contact_id IS NULL AND staged_crm_contact_id IS NOT NULL)
    OR (current_organisation_id IS NULL AND staged_organisation_id IS NOT NULL));

-- Counts before the fix, for a sanity check against the "after" counts in VERIFY
SELECT COUNT(*) AS users_with_crm_info_before
FROM users
WHERE crm_contact_id IS NOT NULL
   OR organisation_id IS NOT NULL;

-- ============================================================================
-- STATEMENTS TO BE EXECUTED -- individual UPDATE statements, for manual/visual inspection
-- before FIX runs. This is exactly what FIX (below) will do, row by row.
-- ============================================================================

SELECT CONCAT('UPDATE users SET crm_contact_id = ', COALESCE(QUOTE(new_crm_contact_id), 'NULL'),
              ', organisation_id = ', COALESCE(CAST(new_organisation_id AS CHAR), 'NULL'),
              ' WHERE id = ', target_id, ';') AS statement
FROM crm_restore_map
WHERE has_unique_conflict = FALSE
  AND ((current_crm_contact_id IS NULL AND staged_crm_contact_id IS NOT NULL)
    OR (current_organisation_id IS NULL AND staged_organisation_id IS NOT NULL))
ORDER BY target_id;

-- ============================================================================
-- FIX -- only proceed once the dry-run and statement output above have been reviewed
-- ============================================================================

UPDATE users u
    JOIN crm_restore_map m ON u.id = m.target_id
    SET u.crm_contact_id  = m.new_crm_contact_id,
        u.organisation_id = m.new_organisation_id
WHERE m.has_unique_conflict = FALSE
  AND ((m.current_crm_contact_id IS NULL AND m.staged_crm_contact_id IS NOT NULL)
    OR (m.current_organisation_id IS NULL AND m.staged_organisation_id IS NOT NULL));

-- ============================================================================
-- VERIFY
-- ============================================================================

-- Should be empty, or match only rows already flagged as field-level/unique conflicts above
SELECT m.target_id, m.target_sub,
       m.staged_crm_contact_id, u.crm_contact_id AS current_crm_contact_id,
       m.staged_organisation_id, u.organisation_id AS current_organisation_id
FROM crm_restore_map m
         JOIN users u ON u.id = m.target_id
WHERE (m.staged_crm_contact_id IS NOT NULL AND
       (u.crm_contact_id IS NULL OR u.crm_contact_id <> m.staged_crm_contact_id))
   OR (m.staged_organisation_id IS NOT NULL AND
       (u.organisation_id IS NULL OR u.organisation_id <> m.staged_organisation_id));

-- Counts after the fix, to compare against the "before" count above
SELECT COUNT(*) AS users_with_crm_info_after
FROM users
WHERE crm_contact_id IS NOT NULL
   OR organisation_id IS NOT NULL;

DROP TEMPORARY TABLE crm_restore_map;
DROP TABLE crm_restore_staging;
